//=========================================================
// src/big_battery_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8BB1_Register_Enums.h>                  // SFR declarations
#include "InitDevice.h"
// $[Generated Includes]
// [Generated Includes]$



//-----------------------------------------------------------------------------
// Global CONSTANTS
//-----------------------------------------------------------------------------
SI_SBIT(TRICKLE_DIS, SFR_P0, 2);               // P0.2 Trickle Disable
SI_SBIT(OUTPUT_EN, SFR_P0, 7);               // P0.7 Output Enable


//-----------------------------------------------------------------------------
// Externs
//-----------------------------------------------------------------------------
extern uint8_t TX_BUFFER[UART_BUFFERSIZE];
extern uint8_t RX_BUFFER[UART_BUFFERSIZE];
extern uint8_t TX_index;
extern uint8_t TX_size;
extern uint8_t RX_size;
extern uint8_t UART_Output_First;
extern uint8_t TX_Ready;
extern uint8_t Byte;

void uart_write(char * buf);
void set_pwm0(uint16_t duty);

//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void SiLabs_Startup (void)
{
  // $[SiLabs Startup]
  // [SiLabs Startup]$
}

//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int main (void) {
	// Call hardware initialization routine
	uint16_t duty = 0;
	enter_DefaultMode_from_RESET();

	TRICKLE_DIS = 1;
	OUTPUT_EN = 1;

	while(1) {
	// $[Generated Run-time code]
	// [Generated Run-time code]$
		uart_write("this is a test");
		while(!TX_Ready);
		set_pwm0(duty);
		if(duty < 2048) {
			duty++;
		} else {
			duty = 0;
		}
		if(duty % 10 == 0) {
			TRICKLE_DIS = ~TRICKLE_DIS;
			OUTPUT_EN = ~OUTPUT_EN;

		}
	}
}


void uart_write(char * buf) {
	TX_Ready = 0;
	TX_size = 0;
	while((buf[TX_size] != '\n') && (TX_size < UART_BUFFERSIZE)) {
		TX_BUFFER[TX_size] = buf[TX_size];
		TX_size++;
	}
	SBUF0 = TX_BUFFER[0];
}

void set_pwm0(uint16_t duty) {
   PCA0PWM |= 0x80;                    // Target Auto-reload registers

   PCA0CPL0 = (duty & 0x00FF);
   PCA0CPH0 = (duty & 0xFF00)>>8;

   PCA0PWM &= ~0x80;                   // Target PCA0CPH/L registers
}

