//=========================================================
// src/big_battery_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8BB1_Register_Enums.h>                  // SFR declarations
#include "InitDevice.h"
// $[Generated Includes]
// [Generated Includes]$



//-----------------------------------------------------------------------------
// Externs
//-----------------------------------------------------------------------------
extern uint8_t TX_BUFFER[UART_BUFFERSIZE];
extern uint8_t RX_BUFFER[UART_BUFFERSIZE];
extern uint8_t TX_index;
extern uint8_t TX_size;
extern uint8_t RX_size;
extern uint8_t UART_Output_First;
extern uint8_t TX_Ready;
extern uint8_t Byte;


void uart_write(char * buf);

//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void SiLabs_Startup (void)
{
  // $[SiLabs Startup]
  // [SiLabs Startup]$
}

//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int main (void) {
	// Call hardware initialization routine
	enter_DefaultMode_from_RESET();

	while(1) {
	// $[Generated Run-time code]
	// [Generated Run-time code]$
		uart_write("this is a test");
		while(!TX_Ready);
	}
}


void uart_write(char * buf) {
	TX_Ready = 0;
	TX_size = 0;
	while((buf[TX_size] != '\n') && (TX_size < UART_BUFFERSIZE)) {
		TX_BUFFER[TX_size] = buf[TX_size];
		TX_size++;
	}
	SBUF0 = TX_BUFFER[0];
}

